TRAIN_DATA_LOC = r'..\data\01_raw\seg_train'
TEST_DATA_LOC = r'..\data\01_raw\seg_test'
PRED_DATA_LOC = r'..\data\01_raw\seg_pred'
ANNOT_LOC = r'..\data\02_intermediate'
MODEL_SAVE_LOC = r'..\data\04_model'
REPORT_SAVE_LOC = r'..\data\06_reporting'